---
- hosts: localhost
  module_defaults:
    ansible.builtin.setup:
      fact_path: "/srv/git/saltbox/ansible_facts.d"
  vars_files:
    - settings.yml
    - ['/srv/git/saltbox/accounts.yml', '/srv/git/saltbox/defaults/accounts.yml.default']
    - ['/srv/git/saltbox/settings.yml', '/srv/git/saltbox/defaults/settings.yml.default']
    - ['/srv/git/saltbox/adv_settings.yml', '/srv/git/saltbox/defaults/adv_settings.yml.default']
  roles:
    - { role: pre_tasks }
    - { role: myrole, tags: ['myrole'] }
    - { role: helloworld, tags: ['helloworld'] }
    - { role: crowdsec, tags: ['crowdsec'] }
    - { role: flame, tags: ['flame'] }
    - { role: immich, tags: ['immich'] }
    - { role: immich_microservices, tags: ['immich_microservices'] }
    - { role: immich_machine_learning, tags: ['immich_machine_learning'] }
    - { role: immich_typesense, tags: ['immich_typesense'] }
    - { role: maintainerr, tags: ['maintainerr'] }
    - { role: profilarr, tags: ['profilarr', 'profilarr-backup', 'profilarr-reset'] }
    - { role: spotweb, tags: ['spotweb'] }
    - { role: zigbee2mqtt, tags: ['zigbee2mqtt'] }
    - { role: mariadb-backup, tags: ['mariadb-backup']}
    - { role: postgres-backup, tags: ['postgres-backup']}
