##########################################################################
# Title:            Sandbox: immich_microservices | Default Variables                  #
# Author(s):        CHAIR/Raneydazed                                     #
# URL:              https://github.com/saltyorg/Sandbox                  #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

immich_microservices_name: immich_microservices

################################
# Paths
################################

immich_microservices_paths_folder: "{{ immich_microservices_name }}"
immich_microservices_paths_location: "{{ server_appdata_path }}/{{ immich_microservices_paths_folder }}"
immich_microservices_paths_folders_list:
  - "{{ immich_microservices_paths_location }}"
  - "/mnt/local/Media/Photos"

################################
# Docker
################################

# Container
immich_microservices_docker_container: "{{ immich_microservices_name }}"

# Image
immich_microservices_docker_image_pull: true
immich_microservices_docker_image_tag: "release"
immich_microservices_docker_image: "ghcr.io/immich-app/immich-server:{{ immich_microservices_docker_image_tag }}"

# Ports
immich_microservices_docker_ports_defaults: []
immich_microservices_docker_ports_custom: []
immich_microservices_docker_ports: "{{ immich_microservices_docker_ports_defaults
                                       + immich_microservices_docker_ports_custom }}"

# Envs
immich_microservices_docker_envs_default: {}
immich_microservices_docker_envs_custom: {}
immich_microservices_docker_envs: "{{ immich_microservices_docker_envs_default
                                      | combine(immich_microservices_docker_envs_custom) }}"

# Commands
immich_microservices_docker_commands_default:
  - "start.sh"
  - "microservices"
immich_microservices_docker_commands_custom: []
immich_microservices_docker_commands: "{{ immich_microservices_docker_commands_default
                                          + immich_microservices_docker_commands_custom }}"

# Volumes
immich_microservices_docker_volumes_default: 
  - "/etc/localtime:/etc/localtime:ro"
immich_microservices_docker_volumes_custom: []
immich_microservices_docker_volumes: "{{ immich_microservices_docker_volumes_default
                                         + immich_microservices_docker_volumes_custom }}"

# Devices
immich_microservices_docker_devices_default: []
immich_microservices_docker_devices_custom: []
immich_microservices_docker_devices: "{{ immich_microservices_docker_devices_default
                                         + immich_microservices_docker_devices_custom }}"

# Hosts
immich_microservices_docker_hosts_default: []
immich_microservices_docker_hosts_custom: []
immich_microservices_docker_hosts: "{{ docker_hosts_common
                                       | combine(immich_microservices_docker_hosts_default)
                                       | combine(immich_microservices_docker_hosts_custom) }}"

# Labels
immich_microservices_docker_labels_default: {}
immich_microservices_docker_labels_custom: {}
immich_microservices_docker_labels: "{{ docker_labels_common
                                        | combine(immich_microservices_docker_labels_default)
                                        | combine(immich_microservices_docker_labels_custom) }}"

# Hostname
immich_microservices_docker_hostname: "{{ immich_microservices_name }}"

# Networks
immich_microservices_docker_networks_alias: "{{ immich_microservices_name }}"
immich_microservices_docker_networks_default: []
immich_microservices_docker_networks_custom: []
immich_microservices_docker_networks: "{{ docker_networks_common
                                          + immich_microservices_docker_networks_default
                                          + immich_microservices_docker_networks_custom }}"

# Capabilities
immich_microservices_docker_capabilities_default: []
immich_microservices_docker_capabilities_custom: []
immich_microservices_docker_capabilities: "{{ immich_microservices_docker_capabilities_default
                                              + immich_microservices_docker_capabilities_custom }}"

# Security Opts
immich_microservices_docker_security_opts_default: []
immich_microservices_docker_security_opts_custom: []
immich_microservices_docker_security_opts: "{{ immich_microservices_docker_security_opts_default
                                               + immich_microservices_docker_security_opts_custom }}"

# Restart Policy
immich_microservices_docker_restart_policy: unless-stopped

# State
immich_microservices_docker_state: started

# User Map
immich_microservices_docker_user: "{{ uid }}:{{ gid }}"
